//
// Copyright 2014-2016 Amazon.com,
// Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Amazon Software License (the "License").
// You may not use this file except in compliance with the
// License. A copy of the License is located at
//
//     http://aws.amazon.com/asl/
//
// or in the "license" file accompanying this file. This file is
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, express or implied. See the License
// for the specific language governing permissions and
// limitations under the License.
//

#import <Foundation/Foundation.h>

/*!
 Project version number for the AWSCognito framework.

 @warning This value is deprecated and will be removed in an upcoming minor
 version of the SDK. It conflicts with the umbrella header generated by
 CocoaPods, and is not implemented at all in cases where this SDK is imported
 as a CocoaPod static library. As this numeric value does not support
 patch-level versioning, you should use AWSCognitoSDKVersion instead.
 @deprecated Use AWSCognitoSDKVersion instead.
 */
FOUNDATION_EXPORT double AWSCognitoVersionNumber DEPRECATED_MSG_ATTRIBUTE("Use AWSCognitoSDKVersion instead.");

/*!
 Project version string for the AWSCognito framework.

 @warning This value is deprecated and will be removed in an upcoming minor
 version of the SDK. It conflicts with the umbrella header generated by
 CocoaPods, and is not implemented at all in cases where this SDK is imported
 as a CocoaPod static library.
 @deprecated Use AWSCognitoSDKVersion instead.
 */
FOUNDATION_EXPORT const unsigned char AWSCognitoVersionString[] DEPRECATED_MSG_ATTRIBUTE("Use AWSCognitoSDKVersion instead.");

#import "AWSCognitoService.h"
#import "AWSCognitoDataset.h"
#import "AWSCognitoRecord.h"
#import "AWSCognitoHandlers.h"
#import "AWSCognitoConflict.h"
#import "AWSCognitoSyncService.h"
