site_name: AWS Mobile SDK for iOS
pages:
- Home: 'index.md'
- Setup: 
  - Dependencies: 'setup/setup-dependencies.md'
  - Application: 'setup/setup-application.md'
- Working with Service Clients: 'service-clients.md'
- S3 Transfer Utility: 
  - TransferUtility Setup: 's3/s3-setup.md'
  - Upload: 's3/s3-uploads.md'
  - Download: 's3/s3-downloads.md'
- Sample Apps:  'samples-info.md'
- Logging: 'logging.md'
- AWSTask: 'awstask.md'
theme: 
  name: 'material'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/aws'
    - type: 'twitter'
      link: 'https://twitter.com/awsformobile'
markdown_extensions:
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.betterem:
      smart_enable: all