source 'https://github.com/CocoaPods/Specs.git'

pod 'Bolts', '~> 1.1.0'
pod 'Mantle', '~> 1.4'
pod 'TMCache', '~> 1.2.1'
pod 'XMLDictionary', '~> 1.4.0'
pod 'UICKeyChainStore', '~> 1.0'
pod 'Reachability', '~> 3.1'
pod 'GZIP', '~> 1.0.3'
pod 'FMDB', '~> 2.4.0'
