//
// Copyright 2010-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// A copy of the License is located at
//
// http://aws.amazon.com/apache2.0
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

#import "AWSCognitoIdentityProviderResources.h"
#import "AWSLogging.h"

@interface AWSCognitoIdentityProviderResources ()

@property (nonatomic, strong) NSDictionary *definitionDictionary;

@end

@implementation AWSCognitoIdentityProviderResources

+ (instancetype)sharedInstance {
    static AWSCognitoIdentityProviderResources *_sharedResources = nil;
    static dispatch_once_t once_token;

    dispatch_once(&once_token, ^{
        _sharedResources = [AWSCognitoIdentityProviderResources new];
    });

    return _sharedResources;
}
- (NSDictionary *)JSONObject {
    return self.definitionDictionary;
}

- (instancetype)init {
    if (self = [super init]) {
        //init method
        NSError *error = nil;
        _definitionDictionary = [NSJSONSerialization JSONObjectWithData:[[self definitionString] dataUsingEncoding:NSUTF8StringEncoding]
                                                                options:kNilOptions
                                                                  error:&error];
        if (_definitionDictionary == nil) {
            if (error) {
                AWSLogError(@"Failed to parse JSON service definition: %@",error);
            }
        }
    }
    return self;
}

- (NSString *)definitionString {
    return @" \
    { \
    \"version\":\"2.0\", \
    \"metadata\":{ \
    \"apiVersion\":\"2016-04-18\", \
    \"endpointPrefix\":\"cognito-idp\", \
    \"jsonVersion\":\"1.1\", \
    \"protocol\":\"json\", \
    \"serviceFullName\":\"AWSCognitoIdentityProviderService\", \
    \"signatureVersion\":\"v4\", \
    \"targetPrefix\":\"AWSCognitoIdentityProviderService\" \
    }, \
    \"operations\":{ \
    \"AddCustomAttributes\":{ \
    \"name\":\"AddCustomAttributes\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AddCustomAttributesRequest\"}, \
    \"output\":{\"shape\":\"AddCustomAttributesResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminConfirmSignUp\":{ \
    \"name\":\"AdminConfirmSignUp\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminConfirmSignUpRequest\"}, \
    \"output\":{\"shape\":\"AdminConfirmSignUpResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyFailedAttemptsException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminDeleteUser\":{ \
    \"name\":\"AdminDeleteUser\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminDeleteUserRequest\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminDeleteUserAttributes\":{ \
    \"name\":\"AdminDeleteUserAttributes\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminDeleteUserAttributesRequest\"}, \
    \"output\":{\"shape\":\"AdminDeleteUserAttributesResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminDisableUser\":{ \
    \"name\":\"AdminDisableUser\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminDisableUserRequest\"}, \
    \"output\":{\"shape\":\"AdminDisableUserResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminEnableUser\":{ \
    \"name\":\"AdminEnableUser\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminEnableUserRequest\"}, \
    \"output\":{\"shape\":\"AdminEnableUserResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminGetUser\":{ \
    \"name\":\"AdminGetUser\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminGetUserRequest\"}, \
    \"output\":{\"shape\":\"AdminGetUserResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminResetUserPassword\":{ \
    \"name\":\"AdminResetUserPassword\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminResetUserPasswordRequest\"}, \
    \"output\":{\"shape\":\"AdminResetUserPasswordResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"AdminSetUserSettings\":{ \
    \"name\":\"AdminSetUserSettings\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminSetUserSettingsRequest\"}, \
    \"output\":{\"shape\":\"AdminSetUserSettingsResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"} \
    ] \
    }, \
    \"AdminUpdateUserAttributes\":{ \
    \"name\":\"AdminUpdateUserAttributes\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AdminUpdateUserAttributesRequest\"}, \
    \"output\":{\"shape\":\"AdminUpdateUserAttributesResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"AliasExistsException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"Authenticate\":{ \
    \"name\":\"Authenticate\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"AuthenticateRequest\"}, \
    \"output\":{\"shape\":\"AuthenticateResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ChangePassword\":{ \
    \"name\":\"ChangePassword\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ChangePasswordRequest\"}, \
    \"output\":{\"shape\":\"ChangePasswordResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"InvalidPasswordException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ConfirmForgotPassword\":{ \
    \"name\":\"ConfirmForgotPassword\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ConfirmForgotPasswordRequest\"}, \
    \"output\":{\"shape\":\"ConfirmForgotPasswordResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"InvalidPasswordException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"CodeMismatchException\"}, \
    {\"shape\":\"ExpiredCodeException\"}, \
    {\"shape\":\"TooManyFailedAttemptsException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ConfirmSignUp\":{ \
    \"name\":\"ConfirmSignUp\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ConfirmSignUpRequest\"}, \
    \"output\":{\"shape\":\"ConfirmSignUpResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyFailedAttemptsException\"}, \
    {\"shape\":\"CodeMismatchException\"}, \
    {\"shape\":\"ExpiredCodeException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"AliasExistsException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"CreateUserPool\":{ \
    \"name\":\"CreateUserPool\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"CreateUserPoolRequest\"}, \
    \"output\":{\"shape\":\"CreateUserPoolResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"CreateUserPoolClient\":{ \
    \"name\":\"CreateUserPoolClient\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"CreateUserPoolClientRequest\"}, \
    \"output\":{\"shape\":\"CreateUserPoolClientResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"DeleteUser\":{ \
    \"name\":\"DeleteUser\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"DeleteUserRequest\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"DeleteUserAttributes\":{ \
    \"name\":\"DeleteUserAttributes\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"DeleteUserAttributesRequest\"}, \
    \"output\":{\"shape\":\"DeleteUserAttributesResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"DeleteUserPool\":{ \
    \"name\":\"DeleteUserPool\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"DeleteUserPoolRequest\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"DeleteUserPoolClient\":{ \
    \"name\":\"DeleteUserPoolClient\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"DeleteUserPoolClientRequest\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"DescribeUserPool\":{ \
    \"name\":\"DescribeUserPool\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"DescribeUserPoolRequest\"}, \
    \"output\":{\"shape\":\"DescribeUserPoolResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"DescribeUserPoolClient\":{ \
    \"name\":\"DescribeUserPoolClient\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"DescribeUserPoolClientRequest\"}, \
    \"output\":{\"shape\":\"DescribeUserPoolClientResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"EnhanceAuth\":{ \
    \"name\":\"EnhanceAuth\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"EnhanceAuthRequest\"}, \
    \"output\":{\"shape\":\"EnhanceAuthResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"CodeMismatchException\"}, \
    {\"shape\":\"ExpiredCodeException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ForgotPassword\":{ \
    \"name\":\"ForgotPassword\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ForgotPasswordRequest\"}, \
    \"output\":{\"shape\":\"ForgotPasswordResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"GetAuthenticationDetails\":{ \
    \"name\":\"GetAuthenticationDetails\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"GetAuthenticationDetailsRequest\"}, \
    \"output\":{\"shape\":\"GetAuthenticationDetailsResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"GetJWKS\":{ \
    \"name\":\"GetJWKS\", \
    \"http\":{ \
    \"method\":\"GET\", \
    \"requestUri\":\"/{userPoolId}/.well-known/jwks.json\", \
    \"responseCode\":200 \
    }, \
    \"input\":{\"shape\":\"GetJWKSRequest\"}, \
    \"output\":{\"shape\":\"GetJWKSResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"GetOpenIdConfiguration\":{ \
    \"name\":\"GetOpenIdConfiguration\", \
    \"http\":{ \
    \"method\":\"GET\", \
    \"requestUri\":\"/{userPoolId}/.well-known/openid-configuration\", \
    \"responseCode\":200 \
    }, \
    \"input\":{\"shape\":\"GetOpenIdConfigurationRequest\"}, \
    \"output\":{\"shape\":\"GetOpenIdConfigurationResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"GetUser\":{ \
    \"name\":\"GetUser\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"GetUserRequest\"}, \
    \"output\":{\"shape\":\"GetUserResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"GetUserAttributeVerificationCode\":{ \
    \"name\":\"GetUserAttributeVerificationCode\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"GetUserAttributeVerificationCodeRequest\"}, \
    \"output\":{\"shape\":\"GetUserAttributeVerificationCodeResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ListUserPoolClients\":{ \
    \"name\":\"ListUserPoolClients\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ListUserPoolClientsRequest\"}, \
    \"output\":{\"shape\":\"ListUserPoolClientsResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ListUserPools\":{ \
    \"name\":\"ListUserPools\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ListUserPoolsRequest\"}, \
    \"output\":{\"shape\":\"ListUserPoolsResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ListUsers\":{ \
    \"name\":\"ListUsers\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ListUsersRequest\"}, \
    \"output\":{\"shape\":\"ListUsersResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"RefreshTokens\":{ \
    \"name\":\"RefreshTokens\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"RefreshTokensRequest\"}, \
    \"output\":{\"shape\":\"RefreshTokensResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"ResendConfirmationCode\":{ \
    \"name\":\"ResendConfirmationCode\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"ResendConfirmationCodeRequest\"}, \
    \"output\":{\"shape\":\"ResendConfirmationCodeResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"SetUserSettings\":{ \
    \"name\":\"SetUserSettings\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"SetUserSettingsRequest\"}, \
    \"output\":{\"shape\":\"SetUserSettingsResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"NotAuthorizedException\"} \
    ] \
    }, \
    \"SignUp\":{ \
    \"name\":\"SignUp\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"SignUpRequest\"}, \
    \"output\":{\"shape\":\"SignUpResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"InvalidPasswordException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"UpdateUserAttributes\":{ \
    \"name\":\"UpdateUserAttributes\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"UpdateUserAttributesRequest\"}, \
    \"output\":{\"shape\":\"UpdateUserAttributesResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"CodeMismatchException\"}, \
    {\"shape\":\"ExpiredCodeException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"UnexpectedLambdaException\"}, \
    {\"shape\":\"UserLambdaValidationException\"}, \
    {\"shape\":\"InvalidLambdaResponseException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"AliasExistsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"UpdateUserPool\":{ \
    \"name\":\"UpdateUserPool\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"UpdateUserPoolRequest\"}, \
    \"output\":{\"shape\":\"UpdateUserPoolResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"ConcurrentModificationException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"UpdateUserPoolClient\":{ \
    \"name\":\"UpdateUserPoolClient\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"UpdateUserPoolClientRequest\"}, \
    \"output\":{\"shape\":\"UpdateUserPoolClientResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    }, \
    \"VerifyUserAttribute\":{ \
    \"name\":\"VerifyUserAttribute\", \
    \"http\":{ \
    \"method\":\"POST\", \
    \"requestUri\":\"/\" \
    }, \
    \"input\":{\"shape\":\"VerifyUserAttributeRequest\"}, \
    \"output\":{\"shape\":\"VerifyUserAttributeResponse\"}, \
    \"errors\":[ \
    {\"shape\":\"ResourceNotFoundException\"}, \
    {\"shape\":\"InvalidParameterException\"}, \
    {\"shape\":\"CodeMismatchException\"}, \
    {\"shape\":\"ExpiredCodeException\"}, \
    {\"shape\":\"NotAuthorizedException\"}, \
    {\"shape\":\"TooManyRequestsException\"}, \
    {\"shape\":\"InternalErrorException\"} \
    ] \
    } \
    }, \
    \"shapes\":{ \
    \"AddCustomAttributesRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"CustomAttributes\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"CustomAttributes\":{\"shape\":\"CustomAttributesListType\"} \
    } \
    }, \
    \"AddCustomAttributesResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminConfirmSignUpRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"AdminConfirmSignUpResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminDeleteUserAttributesRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\", \
    \"UserAttributeNames\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"UserAttributeNames\":{\"shape\":\"AttributeNameListType\"} \
    } \
    }, \
    \"AdminDeleteUserAttributesResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminDeleteUserRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"AdminDisableUserRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"AdminDisableUserResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminEnableUserRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"AdminEnableUserResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminGetUserRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"AdminGetUserResponse\":{ \
    \"type\":\"structure\", \
    \"required\":[\"Username\"], \
    \"members\":{ \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"UserAttributes\":{\"shape\":\"AttributeListType\"}, \
    \"UserCreateDate\":{\"shape\":\"DateType\"}, \
    \"UserLastModifiedDate\":{\"shape\":\"DateType\"}, \
    \"Enabled\":{\"shape\":\"BooleanType\"}, \
    \"UserStatus\":{\"shape\":\"UserStatusType\"}, \
    \"MFAOptions\":{\"shape\":\"MFAOptionListType\"} \
    } \
    }, \
    \"AdminResetUserPasswordRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"AdminResetUserPasswordResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminSetUserSettingsRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\", \
    \"MFAOptions\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"MFAOptions\":{\"shape\":\"MFAOptionListType\"} \
    } \
    }, \
    \"AdminSetUserSettingsResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AdminUpdateUserAttributesRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"Username\", \
    \"UserAttributes\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"UserAttributes\":{\"shape\":\"AttributeListType\"} \
    } \
    }, \
    \"AdminUpdateUserAttributesResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"AliasAttributeType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"phone_number\", \
    \"email\", \
    \"preferred_username\" \
    ] \
    }, \
    \"AliasAttributesListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"AliasAttributeType\"} \
    }, \
    \"AliasExistsException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"ArnType\":{ \
    \"type\":\"string\", \
    \"max\":2048, \
    \"min\":20 \
    }, \
    \"AttributeDataType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"String\", \
    \"Number\", \
    \"DateTime\", \
    \"Boolean\" \
    ] \
    }, \
    \"AttributeListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"AttributeType\"} \
    }, \
    \"AttributeNameListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"AttributeNameType\"} \
    }, \
    \"AttributeNameType\":{ \
    \"type\":\"string\", \
    \"max\":124, \
    \"min\":1, \
    \"pattern\":\"[\\\\p{L}\\\\p{M}\\\\p{S}\\\\p{N}\\\\p{P}]+\" \
    }, \
    \"AttributeType\":{ \
    \"type\":\"structure\", \
    \"required\":[\"Name\"], \
    \"members\":{ \
    \"Name\":{\"shape\":\"AttributeNameType\"}, \
    \"Value\":{\"shape\":\"AttributeValueType\"} \
    } \
    }, \
    \"AttributeValueType\":{ \
    \"type\":\"string\", \
    \"max\":1024, \
    \"sensitive\":true \
    }, \
    \"AuthStateType\":{ \
    \"type\":\"string\", \
    \"sensitive\":true \
    }, \
    \"AuthenticateRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\", \
    \"PasswordClaim\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"PasswordClaim\":{\"shape\":\"PasswordClaimType\"}, \
    \"Timestamp\":{\"shape\":\"DateType\"} \
    } \
    }, \
    \"AuthenticateResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"AuthenticationResult\":{\"shape\":\"AuthenticationResultType\"}, \
    \"AuthState\":{\"shape\":\"AuthStateType\"}, \
    \"CodeDeliveryDetails\":{\"shape\":\"CodeDeliveryDetailsType\"} \
    } \
    }, \
    \"AuthenticationResultType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"AccessToken\":{\"shape\":\"TokenModelType\"}, \
    \"ExpiresIn\":{\"shape\":\"IntegerType\"}, \
    \"TokenType\":{\"shape\":\"StringType\"}, \
    \"RefreshToken\":{\"shape\":\"TokenModelType\"}, \
    \"IdToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"BlobType\":{\"type\":\"blob\"}, \
    \"BooleanType\":{\"type\":\"boolean\"}, \
    \"ChangePasswordRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"PreviousPassword\", \
    \"ProposedPassword\" \
    ], \
    \"members\":{ \
    \"PreviousPassword\":{\"shape\":\"PasswordType\"}, \
    \"ProposedPassword\":{\"shape\":\"PasswordType\"}, \
    \"AccessToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"ChangePasswordResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"ClientIdType\":{ \
    \"type\":\"string\", \
    \"max\":128, \
    \"min\":1, \
    \"pattern\":\"[\\\\w+]+\", \
    \"sensitive\":true \
    }, \
    \"ClientNameType\":{ \
    \"type\":\"string\", \
    \"max\":128, \
    \"min\":1, \
    \"pattern\":\"[\\\\w\\\\s+=,.@-]+\" \
    }, \
    \"ClientSecretType\":{ \
    \"type\":\"string\", \
    \"max\":64, \
    \"min\":1, \
    \"pattern\":\"[\\\\w+]+\", \
    \"sensitive\":true \
    }, \
    \"CodeDeliveryDetailsListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"CodeDeliveryDetailsType\"} \
    }, \
    \"CodeDeliveryDetailsType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"Destination\":{\"shape\":\"StringType\"}, \
    \"DeliveryMedium\":{\"shape\":\"DeliveryMediumType\"}, \
    \"AttributeName\":{\"shape\":\"AttributeNameType\"} \
    } \
    }, \
    \"CodeMismatchException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"ConcurrentModificationException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"ConfirmForgotPasswordRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\", \
    \"ConfirmationCode\", \
    \"Password\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"ConfirmationCode\":{\"shape\":\"ConfirmationCodeType\"}, \
    \"Password\":{\"shape\":\"PasswordType\"} \
    } \
    }, \
    \"ConfirmForgotPasswordResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"ConfirmSignUpRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\", \
    \"ConfirmationCode\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"ConfirmationCode\":{\"shape\":\"ConfirmationCodeType\"}, \
    \"ForceAliasCreation\":{\"shape\":\"ForceAliasCreation\"} \
    } \
    }, \
    \"ConfirmSignUpResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"ConfirmationCodeType\":{ \
    \"type\":\"string\", \
    \"max\":2048, \
    \"min\":1, \
    \"pattern\":\"[\\\\S]+\" \
    }, \
    \"CreateUserPoolClientRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"ClientName\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"ClientName\":{\"shape\":\"ClientNameType\"}, \
    \"GenerateSecret\":{\"shape\":\"GenerateSecret\"} \
    } \
    }, \
    \"CreateUserPoolClientResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPoolClient\":{\"shape\":\"UserPoolClientType\"} \
    } \
    }, \
    \"CreateUserPoolRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"PoolName\"], \
    \"members\":{ \
    \"PoolName\":{\"shape\":\"UserPoolNameType\"}, \
    \"Policies\":{\"shape\":\"UserPoolPolicyType\"}, \
    \"LambdaConfig\":{\"shape\":\"LambdaConfigType\"}, \
    \"AutoVerifiedAttributes\":{\"shape\":\"VerifiedAttributesListType\"}, \
    \"AliasAttributes\":{\"shape\":\"AliasAttributesListType\"}, \
    \"SmsVerificationMessage\":{\"shape\":\"SmsVerificationMessageType\"}, \
    \"EmailVerificationMessage\":{\"shape\":\"EmailVerificationMessageType\"}, \
    \"EmailVerificationSubject\":{\"shape\":\"EmailVerificationSubjectType\"}, \
    \"SmsAuthenticationMessage\":{\"shape\":\"SmsVerificationMessageType\"}, \
    \"MfaConfiguration\":{\"shape\":\"UserPoolMfaType\"} \
    } \
    }, \
    \"CreateUserPoolResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPool\":{\"shape\":\"UserPoolType\"} \
    } \
    }, \
    \"CustomAttributeNameType\":{ \
    \"type\":\"string\", \
    \"max\":117, \
    \"min\":1, \
    \"pattern\":\"[\\\\p{L}\\\\p{M}\\\\p{S}\\\\p{N}\\\\p{P}]+\" \
    }, \
    \"CustomAttributesListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"SchemaAttributeType\"}, \
    \"max\":25, \
    \"min\":1 \
    }, \
    \"DateType\":{\"type\":\"timestamp\"}, \
    \"DeleteUserAttributesRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserAttributeNames\"], \
    \"members\":{ \
    \"UserAttributeNames\":{\"shape\":\"AttributeNameListType\"}, \
    \"AccessToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"DeleteUserAttributesResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"DeleteUserPoolClientRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"ClientId\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"ClientId\":{\"shape\":\"ClientIdType\"} \
    } \
    }, \
    \"DeleteUserPoolRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"} \
    } \
    }, \
    \"DeleteUserRequest\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"AccessToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"DeliveryMediumType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"SMS\", \
    \"EMAIL\" \
    ] \
    }, \
    \"DescribeUserPoolClientRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"ClientId\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"ClientId\":{\"shape\":\"ClientIdType\"} \
    } \
    }, \
    \"DescribeUserPoolClientResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPoolClient\":{\"shape\":\"UserPoolClientType\"} \
    } \
    }, \
    \"DescribeUserPoolRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"} \
    } \
    }, \
    \"DescribeUserPoolResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPool\":{\"shape\":\"UserPoolType\"} \
    } \
    }, \
    \"EmailVerificationMessageType\":{ \
    \"type\":\"string\", \
    \"max\":2048, \
    \"min\":6, \
    \"pattern\":\"[\\\\p{L}\\\\p{M}\\\\p{S}\\\\p{N}\\\\p{P}\\\\s*]*\\\\{####\\\\}[\\\\p{L}\\\\p{M}\\\\p{S}\\\\p{N}\\\\p{P}\\\\s*]*\" \
    }, \
    \"EmailVerificationSubjectType\":{ \
    \"type\":\"string\", \
    \"max\":140, \
    \"min\":1, \
    \"pattern\":\"[\\\\p{L}\\\\p{M}\\\\p{S}\\\\p{N}\\\\p{P}\\\\s]+\" \
    }, \
    \"EnhanceAuthRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\", \
    \"AuthState\", \
    \"Code\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"AuthState\":{\"shape\":\"AuthStateType\"}, \
    \"Code\":{\"shape\":\"StringType\"} \
    } \
    }, \
    \"EnhanceAuthResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"AuthenticationResult\":{\"shape\":\"AuthenticationResultType\"} \
    } \
    }, \
    \"ExpiredCodeException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"ForceAliasCreation\":{\"type\":\"boolean\"}, \
    \"ForgotPasswordRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"ForgotPasswordResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"CodeDeliveryDetails\":{\"shape\":\"CodeDeliveryDetailsType\"} \
    } \
    }, \
    \"GenerateSecret\":{\"type\":\"boolean\"}, \
    \"GetAuthenticationDetailsRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\", \
    \"SrpA\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"SrpA\":{\"shape\":\"HexStringType\"}, \
    \"ValidationData\":{\"shape\":\"AttributeListType\"} \
    } \
    }, \
    \"GetAuthenticationDetailsResponse\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"Salt\", \
    \"SrpB\", \
    \"SecretBlock\" \
    ], \
    \"members\":{ \
    \"Salt\":{\"shape\":\"HexStringType\"}, \
    \"SrpB\":{\"shape\":\"HexStringType\"}, \
    \"SecretBlock\":{\"shape\":\"BlobType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"GetJWKSRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{ \
    \"shape\":\"UserPoolIdType\", \
    \"location\":\"uri\", \
    \"locationName\":\"userPoolId\" \
    } \
    } \
    }, \
    \"GetJWKSResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"keys\":{\"shape\":\"KeyListType\"} \
    } \
    }, \
    \"GetOpenIdConfigurationRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{ \
    \"shape\":\"UserPoolIdType\", \
    \"location\":\"uri\", \
    \"locationName\":\"userPoolId\" \
    } \
    } \
    }, \
    \"GetOpenIdConfigurationResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"issuer\":{\"shape\":\"openIdUrlType\"}, \
    \"jwks_uri\":{\"shape\":\"openIdUrlType\"}, \
    \"authorization_endpoint\":{\"shape\":\"openIdUrlType\"}, \
    \"subject_types_supported\":{\"shape\":\"openIdListType\"}, \
    \"response_types_supported\":{\"shape\":\"openIdListType\"}, \
    \"id_token_signing_alg_values_supported\":{\"shape\":\"openIdListType\"} \
    } \
    }, \
    \"GetUserAttributeVerificationCodeRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"AttributeName\"], \
    \"members\":{ \
    \"AccessToken\":{\"shape\":\"TokenModelType\"}, \
    \"AttributeName\":{\"shape\":\"AttributeNameType\"} \
    } \
    }, \
    \"GetUserAttributeVerificationCodeResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"CodeDeliveryDetails\":{\"shape\":\"CodeDeliveryDetailsType\"} \
    } \
    }, \
    \"GetUserRequest\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"AccessToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"GetUserResponse\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"Username\", \
    \"UserAttributes\" \
    ], \
    \"members\":{ \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"UserAttributes\":{\"shape\":\"AttributeListType\"}, \
    \"MFAOptions\":{\"shape\":\"MFAOptionListType\"} \
    } \
    }, \
    \"HexStringType\":{ \
    \"type\":\"string\", \
    \"pattern\":\"^[0-9a-fA-F]+$\" \
    }, \
    \"IntegerType\":{\"type\":\"integer\"}, \
    \"InternalErrorException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true, \
    \"fault\":true \
    }, \
    \"InvalidLambdaResponseException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"InvalidParameterException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"InvalidPasswordException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"KeyListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"KeyType\"} \
    }, \
    \"KeyType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"kty\":{\"shape\":\"StringType\"}, \
    \"alg\":{\"shape\":\"StringType\"}, \
    \"use\":{\"shape\":\"StringType\"}, \
    \"kid\":{\"shape\":\"StringType\"}, \
    \"n\":{\"shape\":\"StringType\"}, \
    \"e\":{\"shape\":\"StringType\"} \
    } \
    }, \
    \"LambdaConfigType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"PreSignUp\":{\"shape\":\"ArnType\"}, \
    \"CustomMessage\":{\"shape\":\"ArnType\"}, \
    \"PostConfirmation\":{\"shape\":\"ArnType\"}, \
    \"PreAuthentication\":{\"shape\":\"ArnType\"}, \
    \"PostAuthentication\":{\"shape\":\"ArnType\"} \
    } \
    }, \
    \"ListUserPoolClientsRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"MaxResults\":{\"shape\":\"QueryLimit\"}, \
    \"NextToken\":{\"shape\":\"PaginationKey\"} \
    } \
    }, \
    \"ListUserPoolClientsResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPoolClients\":{\"shape\":\"UserPoolClientListType\"}, \
    \"NextToken\":{\"shape\":\"PaginationKey\"} \
    } \
    }, \
    \"ListUserPoolsRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"MaxResults\"], \
    \"members\":{ \
    \"NextToken\":{\"shape\":\"PaginationKeyType\"}, \
    \"MaxResults\":{\"shape\":\"QueryLimitType\"} \
    } \
    }, \
    \"ListUserPoolsResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPools\":{\"shape\":\"UserPoolListType\"}, \
    \"NextToken\":{\"shape\":\"PaginationKeyType\"} \
    } \
    }, \
    \"ListUsersRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"AttributesToGet\":{\"shape\":\"SearchedAttributeNamesListType\"}, \
    \"Limit\":{\"shape\":\"QueryLimitType\"}, \
    \"PaginationToken\":{\"shape\":\"SearchPaginationTokenType\"}, \
    \"UserStatus\":{\"shape\":\"UserStatusType\"} \
    } \
    }, \
    \"ListUsersResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"Users\":{\"shape\":\"UsersListType\"}, \
    \"PaginationToken\":{\"shape\":\"SearchPaginationTokenType\"} \
    } \
    }, \
    \"MFAOptionListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"MFAOptionType\"} \
    }, \
    \"MFAOptionType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"DeliveryMedium\":{\"shape\":\"DeliveryMediumType\"}, \
    \"AttributeName\":{\"shape\":\"AttributeNameType\"} \
    } \
    }, \
    \"MessageType\":{\"type\":\"string\"}, \
    \"NotAuthorizedException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"NumberAttributeConstraintsType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"MinValue\":{\"shape\":\"StringType\"}, \
    \"MaxValue\":{\"shape\":\"StringType\"} \
    } \
    }, \
    \"PaginationKey\":{ \
    \"type\":\"string\", \
    \"min\":1 \
    }, \
    \"PaginationKeyType\":{ \
    \"type\":\"string\", \
    \"min\":1, \
    \"pattern\":\"[\\\\S]+\" \
    }, \
    \"PasswordClaimType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"SecretBlock\":{\"shape\":\"BlobType\"}, \
    \"Signature\":{\"shape\":\"BlobType\"} \
    }, \
    \"sensitive\":true \
    }, \
    \"PasswordPolicyMinLengthType\":{ \
    \"type\":\"integer\", \
    \"max\":99, \
    \"min\":6 \
    }, \
    \"PasswordPolicyType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"MinimumLength\":{\"shape\":\"PasswordPolicyMinLengthType\"}, \
    \"RequireUppercase\":{\"shape\":\"BooleanType\"}, \
    \"RequireLowercase\":{\"shape\":\"BooleanType\"}, \
    \"RequireNumbers\":{\"shape\":\"BooleanType\"}, \
    \"RequireSymbols\":{\"shape\":\"BooleanType\"} \
    } \
    }, \
    \"PasswordType\":{ \
    \"type\":\"string\", \
    \"max\":1024, \
    \"min\":1, \
    \"pattern\":\"[\\\\S]+\", \
    \"sensitive\":true \
    }, \
    \"QueryLimit\":{ \
    \"type\":\"integer\", \
    \"max\":60, \
    \"min\":1 \
    }, \
    \"QueryLimitType\":{ \
    \"type\":\"integer\", \
    \"max\":60, \
    \"min\":1 \
    }, \
    \"RefreshTokensRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"RefreshToken\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"ClientSecret\":{\"shape\":\"ClientSecretType\"}, \
    \"RefreshToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"RefreshTokensResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"AuthenticationResult\":{\"shape\":\"AuthenticationResultType\"} \
    } \
    }, \
    \"ResendConfirmationCodeRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"} \
    } \
    }, \
    \"ResendConfirmationCodeResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"CodeDeliveryDetails\":{\"shape\":\"CodeDeliveryDetailsType\"} \
    } \
    }, \
    \"ResourceNotFoundException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"SchemaAttributeType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"Name\":{\"shape\":\"CustomAttributeNameType\"}, \
    \"AttributeDataType\":{\"shape\":\"AttributeDataType\"}, \
    \"DeveloperOnlyAttribute\":{\"shape\":\"BooleanType\"}, \
    \"Mutable\":{\"shape\":\"BooleanType\"}, \
    \"Required\":{\"shape\":\"BooleanType\"}, \
    \"NumberAttributeConstraints\":{\"shape\":\"NumberAttributeConstraintsType\"}, \
    \"StringAttributeConstraints\":{\"shape\":\"StringAttributeConstraintsType\"} \
    } \
    }, \
    \"SchemaAttributesListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"SchemaAttributeType\"}, \
    \"max\":50, \
    \"min\":1 \
    }, \
    \"SearchPaginationTokenType\":{ \
    \"type\":\"string\", \
    \"min\":1 \
    }, \
    \"SearchedAttributeNamesListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"AttributeNameType\"} \
    }, \
    \"SecretHashType\":{ \
    \"type\":\"string\", \
    \"max\":128, \
    \"min\":1, \
    \"pattern\":\"[\\\\w+=/]+\", \
    \"sensitive\":true \
    }, \
    \"SetUserSettingsRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"AccessToken\", \
    \"MFAOptions\" \
    ], \
    \"members\":{ \
    \"AccessToken\":{\"shape\":\"TokenModelType\"}, \
    \"MFAOptions\":{\"shape\":\"MFAOptionListType\"} \
    } \
    }, \
    \"SetUserSettingsResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"SignUpRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"ClientId\", \
    \"Username\", \
    \"Password\" \
    ], \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"SecretHash\":{\"shape\":\"SecretHashType\"}, \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"Password\":{\"shape\":\"PasswordType\"}, \
    \"UserAttributes\":{\"shape\":\"AttributeListType\"}, \
    \"ValidationData\":{\"shape\":\"AttributeListType\"} \
    } \
    }, \
    \"SignUpResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserConfirmed\":{\"shape\":\"BooleanType\"}, \
    \"CodeDeliveryDetails\":{\"shape\":\"CodeDeliveryDetailsType\"} \
    } \
    }, \
    \"SmsVerificationMessageType\":{ \
    \"type\":\"string\", \
    \"max\":140, \
    \"min\":6, \
    \"pattern\":\".*\\\\{####\\\\}.*\" \
    }, \
    \"StatusType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"Enabled\", \
    \"Disabled\" \
    ] \
    }, \
    \"StringAttributeConstraintsType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"MinLength\":{\"shape\":\"StringType\"}, \
    \"MaxLength\":{\"shape\":\"StringType\"} \
    } \
    }, \
    \"StringType\":{\"type\":\"string\"}, \
    \"TokenModelType\":{ \
    \"type\":\"string\", \
    \"sensitive\":true \
    }, \
    \"TooManyFailedAttemptsException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"TooManyRequestsException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"UnexpectedLambdaException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"UpdateUserAttributesRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserAttributes\"], \
    \"members\":{ \
    \"UserAttributes\":{\"shape\":\"AttributeListType\"}, \
    \"AccessToken\":{\"shape\":\"TokenModelType\"} \
    } \
    }, \
    \"UpdateUserAttributesResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"CodeDeliveryDetailsList\":{\"shape\":\"CodeDeliveryDetailsListType\"} \
    } \
    }, \
    \"UpdateUserPoolClientRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"UserPoolId\", \
    \"ClientId\" \
    ], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"ClientName\":{\"shape\":\"ClientNameType\"} \
    } \
    }, \
    \"UpdateUserPoolClientResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPoolClient\":{\"shape\":\"UserPoolClientType\"} \
    } \
    }, \
    \"UpdateUserPoolRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[\"UserPoolId\"], \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"Policies\":{\"shape\":\"UserPoolPolicyType\"}, \
    \"LambdaConfig\":{\"shape\":\"LambdaConfigType\"}, \
    \"AutoVerifiedAttributes\":{\"shape\":\"VerifiedAttributesListType\"}, \
    \"SmsVerificationMessage\":{\"shape\":\"SmsVerificationMessageType\"}, \
    \"EmailVerificationMessage\":{\"shape\":\"EmailVerificationMessageType\"}, \
    \"EmailVerificationSubject\":{\"shape\":\"EmailVerificationSubjectType\"}, \
    \"SmsAuthenticationMessage\":{\"shape\":\"SmsVerificationMessageType\"}, \
    \"MfaConfiguration\":{\"shape\":\"UserPoolMfaType\"} \
    } \
    }, \
    \"UpdateUserPoolResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"UserLambdaValidationException\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"message\":{\"shape\":\"MessageType\"} \
    }, \
    \"exception\":true \
    }, \
    \"UserPoolClientDescription\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"ClientName\":{\"shape\":\"ClientNameType\"} \
    } \
    }, \
    \"UserPoolClientListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"UserPoolClientDescription\"} \
    }, \
    \"UserPoolClientType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"UserPoolId\":{\"shape\":\"UserPoolIdType\"}, \
    \"ClientName\":{\"shape\":\"ClientNameType\"}, \
    \"ClientId\":{\"shape\":\"ClientIdType\"}, \
    \"ClientSecret\":{\"shape\":\"ClientSecretType\"}, \
    \"LastModifiedDate\":{\"shape\":\"DateType\"}, \
    \"CreationDate\":{\"shape\":\"DateType\"} \
    } \
    }, \
    \"UserPoolDescriptionType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"Id\":{\"shape\":\"UserPoolIdType\"}, \
    \"Name\":{\"shape\":\"UserPoolNameType\"}, \
    \"LambdaConfig\":{\"shape\":\"LambdaConfigType\"}, \
    \"Status\":{\"shape\":\"StatusType\"}, \
    \"LastModifiedDate\":{\"shape\":\"DateType\"}, \
    \"CreationDate\":{\"shape\":\"DateType\"} \
    } \
    }, \
    \"UserPoolIdType\":{ \
    \"type\":\"string\", \
    \"max\":55, \
    \"min\":1, \
    \"pattern\":\"[\\\\w-]+.[0-9a-zA-Z-]+\" \
    }, \
    \"UserPoolListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"UserPoolDescriptionType\"} \
    }, \
    \"UserPoolMfaType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"OFF\", \
    \"ON\", \
    \"OPTIONAL\" \
    ] \
    }, \
    \"UserPoolNameType\":{ \
    \"type\":\"string\", \
    \"max\":128, \
    \"min\":1, \
    \"pattern\":\"[\\\\w\\\\s+=,.@-]+\" \
    }, \
    \"UserPoolPolicyType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"PasswordPolicy\":{\"shape\":\"PasswordPolicyType\"} \
    } \
    }, \
    \"UserPoolType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"Id\":{\"shape\":\"UserPoolIdType\"}, \
    \"Name\":{\"shape\":\"UserPoolNameType\"}, \
    \"Policies\":{\"shape\":\"UserPoolPolicyType\"}, \
    \"LambdaConfig\":{\"shape\":\"LambdaConfigType\"}, \
    \"Status\":{\"shape\":\"StatusType\"}, \
    \"LastModifiedDate\":{\"shape\":\"DateType\"}, \
    \"CreationDate\":{\"shape\":\"DateType\"}, \
    \"SchemaAttributes\":{\"shape\":\"SchemaAttributesListType\"}, \
    \"AutoVerifiedAttributes\":{\"shape\":\"VerifiedAttributesListType\"}, \
    \"AliasAttributes\":{\"shape\":\"AliasAttributesListType\"}, \
    \"SmsVerificationMessage\":{\"shape\":\"SmsVerificationMessageType\"}, \
    \"EmailVerificationMessage\":{\"shape\":\"EmailVerificationMessageType\"}, \
    \"EmailVerificationSubject\":{\"shape\":\"EmailVerificationSubjectType\"}, \
    \"SmsAuthenticationMessage\":{\"shape\":\"SmsVerificationMessageType\"}, \
    \"MfaConfiguration\":{\"shape\":\"UserPoolMfaType\"} \
    } \
    }, \
    \"UserStatusType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"UNCONFIRMED\", \
    \"CONFIRMED\", \
    \"ARCHIVED\", \
    \"COMPROMISED\", \
    \"UNKNOWN\" \
    ] \
    }, \
    \"UserType\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    \"Username\":{\"shape\":\"UsernameType\"}, \
    \"Attributes\":{\"shape\":\"AttributeListType\"}, \
    \"UserCreateDate\":{\"shape\":\"DateType\"}, \
    \"UserLastModifiedDate\":{\"shape\":\"DateType\"}, \
    \"Enabled\":{\"shape\":\"BooleanType\"}, \
    \"UserStatus\":{\"shape\":\"UserStatusType\"} \
    } \
    }, \
    \"UsernameType\":{ \
    \"type\":\"string\", \
    \"max\":128, \
    \"min\":1, \
    \"pattern\":\"[\\\\p{L}\\\\p{M}\\\\p{S}\\\\p{N}\\\\p{P}]+\", \
    \"sensitive\":true \
    }, \
    \"UsersListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"UserType\"} \
    }, \
    \"VerifiedAttributeType\":{ \
    \"type\":\"string\", \
    \"enum\":[ \
    \"phone_number\", \
    \"email\" \
    ] \
    }, \
    \"VerifiedAttributesListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"VerifiedAttributeType\"} \
    }, \
    \"VerifyUserAttributeRequest\":{ \
    \"type\":\"structure\", \
    \"required\":[ \
    \"AttributeName\", \
    \"Code\" \
    ], \
    \"members\":{ \
    \"AccessToken\":{\"shape\":\"TokenModelType\"}, \
    \"AttributeName\":{\"shape\":\"AttributeNameType\"}, \
    \"Code\":{\"shape\":\"ConfirmationCodeType\"} \
    } \
    }, \
    \"VerifyUserAttributeResponse\":{ \
    \"type\":\"structure\", \
    \"members\":{ \
    } \
    }, \
    \"openIdListType\":{ \
    \"type\":\"list\", \
    \"member\":{\"shape\":\"StringType\"} \
    }, \
    \"openIdUrlType\":{ \
    \"type\":\"string\", \
    \"max\":150, \
    \"min\":1, \
    \"pattern\":\"https://cognito-idp\\\\.amazonaws\\\\.com/[\\\\w\\\\._/-]\" \
    } \
    } \
    } \
    \
    ";
}
@end
