#!/bin/sh


# remove everything generated by this script
function cleanup
{
    rm -rf docs
    rm -rf Documentation   
}


VERSION="2.0.11"
if [ -n $1 ] && [ "$1" == "clean" ];
then
	cleanup
	exit 0
else
	cd "$SOURCE_ROOT"
    
    if [ -d docs ]; 
    then
        cleanup
    fi

    mkdir -p docs
    mkdir -p docs_tmp

    cp -r AutoScaling ./docs_tmp/AutoScaling
    cp -r AWSCore ./docs_tmp/AWSCore
    cp -r CloudWatch ./docs_tmp/CloudWatch
    cp -r DynamoDB ./docs_tmp/DynamoDB
    cp -r EC2 ./docs_tmp/EC2
    cp -r ElasticLoadBalancing ./docs_tmp/ElasticLoadBalancing
    cp -r Kinesis ./docs_tmp/Kinesis
    cp -r S3 ./docs_tmp/S3
    cp -r SES ./docs_tmp/SES
    cp -r SimpleDB ./docs_tmp/SimpleDB
    cp -r SNS ./docs_tmp/SNS
    cp -r SQS ./docs_tmp/SQS

    rm -rf ./docs_tmp/AWSCore/XMLWriter
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/core
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/delivery
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/event
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/monetization
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/session
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/AZCommon/ClientContext
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/include/core
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/include/delivery
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/include/event
    rm -rf ./docs_tmp/AWSCore/MobileAnalytics/include/session

    if [ -d ../AWSiOSSDKCognitoSync ]
    then 
    	cp -r ../AWSiOSSDKCognitoSync/Cognito ./docs_tmp/Cognito
        rm -rf ./docs_tmp/Cognito/Internal
    	cp -r ../AWSiOSSDKCognitoSync/CognitoSync ./docs_tmp/CognitoSync
    fi

    cd docs_tmp

    # generate documenation
    /usr/local/bin/appledoc --verbose 0 --output ../docs --exit-threshold 2 --no-repeat-first-par --explicit-crossref --docset-install-path ../docs --docset-bundle-filename com.amazon.aws.ios.docset --company-id aws.amazon.com --project-name "AWS SDK for iOS v${VERSION}" --project-version "${VERSION}" --project-company "Amazon Web Services, Inc." --create-html --finalize-docset --keep-intermediate-files --index-desc ../aws-sdk-for-ios.markdown ./
    
    # get command execution result
    result=$?
    
    if [ $result != 0 ];
    then
        echo "Building the AWS iOS SDK document FAILED!"
        cleanup;
        exit 1;
    fi

    cd "$SOURCE_ROOT"

	# pack html doc into a zip file
    (cd docs/html; zip -q -r --symlinks ../aws-sdk-ios-docs.zip .)

	# add the zip file to git
    #git add docs/aws-sdk-ios-docs.zip && \
    #git commit -m "Latest Appledoc docs" docs/aws-sdk-ios-docs.zip && \
    #git push origin mainline

    rm -rf Documentation
    mkdir Documentation
    mv docs/html Documentation
    mv docs/com.amazon.aws.ios.docset Documentation
    mv docs/aws-sdk-ios-docs.zip Documentation
    rm -rf docs
    rm -rf docs_tmp

	exit 0
fi
