#!/bin/sh

cd "$SOURCE_ROOT"

FRAMEWORK_VERSION=A


UICKEYCHAINSTORE_TEMPLATE="UICKeyChainStore"

# framework build path
UICKEYCHAINSTORE_TEMPLATE_BUILD_PATH="Build/UICKeyChainStore"

# full name of framework
UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR=$UICKEYCHAINSTORE_TEMPLATE_BUILD_PATH/$UICKEYCHAINSTORE_TEMPLATE.framework


#CSURITemplate
rm -rf $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR

echo "Framework: Setting up directories for UICKeyChainStore..."
mkdir -p $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR
mkdir -p $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Versions
mkdir -p $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Versions/$FRAMEWORK_VERSION
mkdir -p $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Versions/$FRAMEWORK_VERSION/Resources
mkdir -p $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Versions/$FRAMEWORK_VERSION/Headers

echo "Framework: Creating symlinks..."
ln -s $FRAMEWORK_VERSION $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Versions/Current
ln -s Versions/Current/Headers $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Headers
ln -s Versions/Current/Resources $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Resources
ln -s Versions/Current/$UICKEYCHAINSTORE_TEMPLATE $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/$UICKEYCHAINSTORE_TEMPLATE


echo "Framework: Creating library CSURITemplate " 
lipo -create "Pods/build/Debug-iphonesimulator/libPods-${UICKEYCHAINSTORE_TEMPLATE}.a" "Pods/build/Debug64-iphonesimulator/libPods-${UICKEYCHAINSTORE_TEMPLATE}.a" "Pods/build/Release-iphoneos/libPods-${UICKEYCHAINSTORE_TEMPLATE}.a" "Pods/build/Release64-iphoneos/libPods-${UICKEYCHAINSTORE_TEMPLATE}.a" -o "$UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Versions/Current/$UICKEYCHAINSTORE_TEMPLATE"

# copy header file
cp -a Pods/UICKeyChainStore/Lib/*.h  $UICKEYCHAINSTORE_TEMPLATE_FRAMEWORK_DIR/Headers