podpackages = [
    'AWSCore.podspec',

    'AWSAPIGateway.podspec',
    'AWSAutoScaling.podspec',
    'AWSCloudWatch.podspec',
    'AWSCognito.podspec',
    'AWSCognitoAuth.podspec',
    'AWSCognitoIdentityProvider.podspec',
    'AWSCognitoSync.podspec',
    'AWSComprehend.podspec',
    'AWSConnect.podspec',
    'AWSConnectParticipant.podspec',
    'AWSDynamoDB.podspec',
    'AWSEC2.podspec',
    'AWSElasticLoadBalancing.podspec',
    'AWSIoT.podspec',
    'AWSKMS.podspec',
    'AWSKinesis.podspec',
    'AWSKinesisVideo.podspec',
    'AWSKinesisVideoArchivedMedia.podspec',
    'AWSKinesisVideoSignaling.podspec',
    'AWSLambda.podspec',
    'AWSLex.podspec',
    'AWSLogs.podspec',
    'AWSMachineLearning.podspec',
    'AWSMobileAnalytics.podspec',
    'AWSPinpoint.podspec',
    'AWSPolly.podspec',
    'AWSRekognition.podspec',
    'AWSS3.podspec',
    'AWSSES.podspec',
    'AWSSNS.podspec',
    'AWSSQS.podspec',
    'AWSSageMakerRuntime.podspec',
    'AWSSimpleDB.podspec',
    'AWSTextract.podspec',
    'AWSTranscribe.podspec',
    'AWSTranscribeStreaming.podspec',
    'AWSTranslate.podspec',

    'AWSAuthCore.podspec',
    'AWSUserPoolsSignIn.podspec',
    'AWSFacebookSignIn.podspec',
    'AWSGoogleSignIn.podspec',
    'AWSAuthUI.podspec',
    'AWSAuth.podspec',

    'AWSMobileClient.podspec',

    'AWSiOSSDKv2.podspec',

    ]
