//
// Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// A copy of the License is located at
//
// http://aws.amazon.com/apache2.0
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

#import <Foundation/Foundation.h>
#import <AWSCore/AWSNetworking.h>
#import <AWSCore/AWSModel.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSString *const AWSMediatailorErrorDomain;

typedef NS_ENUM(NSInteger, AWSMediatailorErrorType) {
    AWSMediatailorErrorUnknown,
    AWSMediatailorErrorBadRequest,
};

typedef NS_ENUM(NSInteger, AWSMediatailorOriginManifestType) {
    AWSMediatailorOriginManifestTypeUnknown,
    AWSMediatailorOriginManifestTypeSinglePeriod,
    AWSMediatailorOriginManifestTypeMultiPeriod,
};

typedef NS_ENUM(NSInteger, AWSMediatailorMode) {
    AWSMediatailorModeUnknown,
    AWSMediatailorModeOff,
    AWSMediatailorModeBehindLiveEdge,
};

@class AWSMediatailorAvailSuppression;
@class AWSMediatailorBumper;
@class AWSMediatailorCdnConfiguration;
@class AWSMediatailorDashConfiguration;
@class AWSMediatailorDashConfigurationForPut;
@class AWSMediatailorDeletePlaybackConfigurationRequest;
@class AWSMediatailorDeletePlaybackConfigurationResponse;
@class AWSMediatailorEmpty;
@class AWSMediatailorGetPlaybackConfigurationRequest;
@class AWSMediatailorGetPlaybackConfigurationResponse;
@class AWSMediatailorHlsConfiguration;
@class AWSMediatailorListPlaybackConfigurationsRequest;
@class AWSMediatailorListPlaybackConfigurationsResponse;
@class AWSMediatailorListTagsForResourceRequest;
@class AWSMediatailorListTagsForResourceResponse;
@class AWSMediatailorPlaybackConfiguration;
@class AWSMediatailorLivePreRollConfiguration;
@class AWSMediatailorPutPlaybackConfigurationRequest;
@class AWSMediatailorPutPlaybackConfigurationResponse;
@class AWSMediatailorTagResourceRequest;
@class AWSMediatailorTagsModel;
@class AWSMediatailorUntagResourceRequest;

/**
 <p>The configuration for Avail Suppression. Ad suppression can be used to turn off ad personalization in a long manifest, or if a viewer joins mid-break.</p>
 */
@interface AWSMediatailorAvailSuppression : AWSModel


/**
 Sets the mode for avail suppression, also known as ad suppression. By default, ad suppression is off and all ad breaks are filled by MediaTailor with ads or slate.
 */
@property (nonatomic, assign) AWSMediatailorMode mode;

/**
 The avail suppression value is a live edge offset time in HH:MM:SS. MediaTailor won't fill ad breaks on or behind this time in the manifest lookback window. 
 */
@property (nonatomic, strong) NSString * _Nullable value;

@end

/**
 <p>The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. </p>
 */
@interface AWSMediatailorBumper : AWSModel


/**
 <p>The URL for the end bumper asset. </p>
 */
@property (nonatomic, strong) NSString * _Nullable endUrl;

/**
 <p>The URL for the start bumper asset. </p>
 */
@property (nonatomic, strong) NSString * _Nullable startUrl;

@end

/**
 <p>The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management. </p>
 */
@interface AWSMediatailorCdnConfiguration : AWSModel


/**
 <p>A non-default content delivery network (CDN) to serve ad segments. By default, AWS Elemental MediaTailor uses Amazon CloudFront with default cache settings as its CDN for ad segments. To set up an alternate CDN, create a rule in your CDN for the following origin: ads.mediatailor.&lt;region>.amazonaws.com. Then specify the rule's name in this AdSegmentUrlPrefix. When AWS Elemental MediaTailor serves a manifest, it reports your CDN as the source for ad segments.</p>
 */
@property (nonatomic, strong) NSString * _Nullable adSegmentUrlPrefix;

/**
 <p>A content delivery network (CDN) to cache content segments, so that content requests don’t always have to go to the origin server. First, create a rule in your CDN for the content segment origin server. Then specify the rule's name in this ContentSegmentUrlPrefix. When AWS Elemental MediaTailor serves a manifest, it reports your CDN as the source for content segments.</p>
 */
@property (nonatomic, strong) NSString * _Nullable contentSegmentUrlPrefix;

@end

/**
 <p>The configuration for DASH content. </p>
 */
@interface AWSMediatailorDashConfiguration : AWSModel


/**
 <p>The URL generated by MediaTailor to initiate a playback session. The session uses server-side reporting. This setting is ignored in PUT operations. </p>
 */
@property (nonatomic, strong) NSString * _Nullable manifestEndpointPrefix;

/**
 <p>The setting that controls whether MediaTailor includes the Location tag in DASH manifests. MediaTailor populates the Location tag with the URL for manifest update requests, to be used by players that don't support sticky redirects. Disable this if you have CDN routing rules set up for accessing MediaTailor manifests, and you are either using client-side reporting or your players support sticky HTTP redirects. Valid values are DISABLED and EMT_DEFAULT. The EMT_DEFAULT setting enables the inclusion of the tag and is the default value. </p>
 */
@property (nonatomic, strong) NSString * _Nullable mpdLocation;

/**
 <p>The setting that controls whether MediaTailor handles manifests from the origin server as multi-period manifests or single-period manifests. If your origin server produces single-period manifests, set this to SINGLE_PERIOD. The default setting is MULTI_PERIOD. For multi-period manifests, omit this setting or set it to MULTI_PERIOD. </p>
 */
@property (nonatomic, assign) AWSMediatailorOriginManifestType originManifestType;

@end

/**
 <p>The configuration for DASH PUT operations. </p>
 */
@interface AWSMediatailorDashConfigurationForPut : AWSModel


/**
 <p>The setting that controls whether MediaTailor includes the Location tag in DASH manifests. MediaTailor populates the Location tag with the URL for manifest update requests, to be used by players that don't support sticky redirects. Disable this if you have CDN routing rules set up for accessing MediaTailor manifests, and you are either using client-side reporting or your players support sticky HTTP redirects. Valid values are DISABLED and EMT_DEFAULT. The EMT_DEFAULT setting enables the inclusion of the tag and is the default value. </p>
 */
@property (nonatomic, strong) NSString * _Nullable mpdLocation;

/**
 <p>The setting that controls whether MediaTailor handles manifests from the origin server as multi-period manifests or single-period manifests. If your origin server produces single-period manifests, set this to SINGLE_PERIOD. The default setting is MULTI_PERIOD. For multi-period manifests, omit this setting or set it to MULTI_PERIOD. </p>
 */
@property (nonatomic, assign) AWSMediatailorOriginManifestType originManifestType;

@end

/**
 
 */
@interface AWSMediatailorDeletePlaybackConfigurationRequest : AWSRequest


/**
 <p>The identifier for the playback configuration.</p>
 */
@property (nonatomic, strong) NSString * _Nullable name;

@end

/**
 
 */
@interface AWSMediatailorDeletePlaybackConfigurationResponse : AWSModel


@end

/**
 
 */
@interface AWSMediatailorEmpty : AWSModel


@end

/**
 
 */
@interface AWSMediatailorGetPlaybackConfigurationRequest : AWSRequest


/**
 <p>The identifier for the playback configuration.</p>
 */
@property (nonatomic, strong) NSString * _Nullable name;

@end

/**
 
 */
@interface AWSMediatailorGetPlaybackConfigurationResponse : AWSModel


/**
 <p>The URL for the ad decision server (ADS). This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing, you can provide a static VAST URL. The maximum length is 25,000 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable adDecisionServerUrl;

/**
 <p>The configuration for Avail Suppression. Ad suppression can be used to turn off ad personalization in a long manifest, or if a viewer joins mid-break.</p>
 */
@property (nonatomic, strong) AWSMediatailorAvailSuppression * _Nullable availSuppression;

/**
 <p>The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. </p>
 */
@property (nonatomic, strong) AWSMediatailorBumper * _Nullable bumper;

/**
 <p>The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management. </p>
 */
@property (nonatomic, strong) AWSMediatailorCdnConfiguration * _Nullable cdnConfiguration;

/**
 <p>The configuration for DASH content. </p>
 */
@property (nonatomic, strong) AWSMediatailorDashConfiguration * _Nullable dashConfiguration;

/**
 <p>The configuration for HLS content. </p>
 */
@property (nonatomic, strong) AWSMediatailorHlsConfiguration * _Nullable hlsConfiguration;

/**
 <p>The configuration for pre-roll ad insertion.</p>
 */
@property (nonatomic, strong) AWSMediatailorLivePreRollConfiguration * _Nullable livePreRollConfiguration;

/**
 <p>The identifier for the playback configuration.</p>
 */
@property (nonatomic, strong) NSString * _Nullable name;

/**
 <p>The maximum duration of underfilled ad time (in seconds) allowed in an ad break.</p>
 */
@property (nonatomic, strong) NSNumber * _Nullable personalizationThresholdSeconds;

/**
 <p>The Amazon Resource Name (ARN) for the playback configuration. </p>
 */
@property (nonatomic, strong) NSString * _Nullable playbackConfigurationArn;

/**
 <p>The URL that the player accesses to get a manifest from AWS Elemental MediaTailor. This session will use server-side reporting. </p>
 */
@property (nonatomic, strong) NSString * _Nullable playbackEndpointPrefix;

/**
 <p>The URL that the player uses to initialize a session that uses client-side reporting. </p>
 */
@property (nonatomic, strong) NSString * _Nullable sessionInitializationEndpointPrefix;

/**
 <p>The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. AWS Elemental MediaTailor shows the slate to fill in gaps in media content. Configuring the slate is optional for non-VPAID playback configurations. For VPAID, the slate is required because MediaTailor provides it in the slots designated for dynamic ad content. The slate must be a high-quality asset that contains both audio and video. </p>
 */
@property (nonatomic, strong) NSString * _Nullable slateAdUrl;

/**
 <p>The tags assigned to the playback configuration. </p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

/**
 <p>The name that is used to associate this playback configuration with a custom transcode profile. This overrides the dynamic transcoding defaults of MediaTailor. Use this only if you have already set up custom profiles with the help of AWS Support.</p>
 */
@property (nonatomic, strong) NSString * _Nullable transcodeProfileName;

/**
 <p>The URL prefix for the master playlist for the stream, minus the asset ID. The maximum length is 512 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable videoContentSourceUrl;

@end

/**
 <p>The configuration for HLS content. </p>
 */
@interface AWSMediatailorHlsConfiguration : AWSModel


/**
 <p>The URL that is used to initiate a playback session for devices that support Apple HLS. The session uses server-side reporting.</p>
 */
@property (nonatomic, strong) NSString * _Nullable manifestEndpointPrefix;

@end

/**
 
 */
@interface AWSMediatailorListPlaybackConfigurationsRequest : AWSRequest


/**
 <p>Maximum number of records to return. </p>
 */
@property (nonatomic, strong) NSNumber * _Nullable maxResults;

/**
 <p>Pagination token returned by the GET list request when results exceed the maximum allowed. Use the token to fetch the next page of results.</p>
 */
@property (nonatomic, strong) NSString * _Nullable nextToken;

@end

/**
 
 */
@interface AWSMediatailorListPlaybackConfigurationsResponse : AWSModel


/**
 <p>Array of playback configurations. This might be all the available configurations or a subset, depending on the settings that you provide and the total number of configurations stored. </p>
 */
@property (nonatomic, strong) NSArray<AWSMediatailorPlaybackConfiguration *> * _Nullable items;

/**
 <p>Pagination token returned by the GET list request when results exceed the maximum allowed. Use the token to fetch the next page of results.</p>
 */
@property (nonatomic, strong) NSString * _Nullable nextToken;

@end

/**
 
 */
@interface AWSMediatailorListTagsForResourceRequest : AWSRequest


/**
 <p>The Amazon Resource Name (ARN) for the playback configuration. You can get this from the response to any playback configuration request. </p>
 */
@property (nonatomic, strong) NSString * _Nullable resourceArn;

@end

/**
 
 */
@interface AWSMediatailorListTagsForResourceResponse : AWSModel


/**
 <p>A comma-separated list of tag key:value pairs. For example: {"Key1": "Value1","Key2": "Value2"}</p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

@end

/**
 <p>The AWSMediaTailor configuration.</p>
 */
@interface AWSMediatailorPlaybackConfiguration : AWSModel


/**
 <p>The URL for the ad decision server (ADS). This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing, you can provide a static VAST URL. The maximum length is 25,000 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable adDecisionServerUrl;

/**
 <p>The configuration for Avail Suppression. Ad suppression can be used to turn off ad personalization in a long manifest, or if a viewer joins mid-break.</p>
 */
@property (nonatomic, strong) AWSMediatailorAvailSuppression * _Nullable availSuppression;

/**
 <p>The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. </p>
 */
@property (nonatomic, strong) AWSMediatailorBumper * _Nullable bumper;

/**
 <p>The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management. </p>
 */
@property (nonatomic, strong) AWSMediatailorCdnConfiguration * _Nullable cdnConfiguration;

/**
 <p>The configuration for DASH content. </p>
 */
@property (nonatomic, strong) AWSMediatailorDashConfiguration * _Nullable dashConfiguration;

/**
 <p>The configuration for HLS content. </p>
 */
@property (nonatomic, strong) AWSMediatailorHlsConfiguration * _Nullable hlsConfiguration;

/**
 <p>The identifier for the playback configuration.</p>
 */
@property (nonatomic, strong) NSString * _Nullable name;

/**
 <p>The maximum duration of underfilled ad time (in seconds) allowed in an ad break.</p>
 */
@property (nonatomic, strong) NSNumber * _Nullable personalizationThresholdSeconds;

/**
 <p>The Amazon Resource Name (ARN) for the playback configuration. </p>
 */
@property (nonatomic, strong) NSString * _Nullable playbackConfigurationArn;

/**
 <p>The URL that the player accesses to get a manifest from AWS Elemental MediaTailor. This session will use server-side reporting. </p>
 */
@property (nonatomic, strong) NSString * _Nullable playbackEndpointPrefix;

/**
 <p>The URL that the player uses to initialize a session that uses client-side reporting. </p>
 */
@property (nonatomic, strong) NSString * _Nullable sessionInitializationEndpointPrefix;

/**
 <p>The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. AWS Elemental MediaTailor shows the slate to fill in gaps in media content. Configuring the slate is optional for non-VPAID playback configurations. For VPAID, the slate is required because MediaTailor provides it in the slots designated for dynamic ad content. The slate must be a high-quality asset that contains both audio and video. </p>
 */
@property (nonatomic, strong) NSString * _Nullable slateAdUrl;

/**
 <p>The tags assigned to the playback configuration. </p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

/**
 <p>The name that is used to associate this playback configuration with a custom transcode profile. This overrides the dynamic transcoding defaults of MediaTailor. Use this only if you have already set up custom profiles with the help of AWS Support.</p>
 */
@property (nonatomic, strong) NSString * _Nullable transcodeProfileName;

/**
 <p>The URL prefix for the master playlist for the stream, minus the asset ID. The maximum length is 512 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable videoContentSourceUrl;

@end

/**
 <p>The configuration for pre-roll ad insertion.</p>
 */
@interface AWSMediatailorLivePreRollConfiguration : AWSModel


/**
 <p>The URL for the ad decision server (ADS) for pre-roll ads. This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing, you can provide a static VAST URL. The maximum length is 25,000 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable adDecisionServerUrl;

/**
 The maximum allowed duration for the pre-roll ad avail. AWS Elemental MediaTailor won't play pre-roll ads to exceed this duration, regardless of the total duration of ads that the ADS returns.
 */
@property (nonatomic, strong) NSNumber * _Nullable maxDurationSeconds;

@end

/**
 
 */
@interface AWSMediatailorPutPlaybackConfigurationRequest : AWSRequest


/**
 <p>The URL for the ad decision server (ADS). This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing you can provide a static VAST URL. The maximum length is 25,000 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable adDecisionServerUrl;

/**
 <p>The configuration for Avail Suppression. Ad suppression can be used to turn off ad personalization in a long manifest, or if a viewer joins mid-break.</p>
 */
@property (nonatomic, strong) AWSMediatailorAvailSuppression * _Nullable availSuppression;

/**
 <p>The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. </p>
 */
@property (nonatomic, strong) AWSMediatailorBumper * _Nullable bumper;

/**
 <p>The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management. </p>
 */
@property (nonatomic, strong) AWSMediatailorCdnConfiguration * _Nullable cdnConfiguration;

/**
 <p>The configuration for DASH content. </p>
 */
@property (nonatomic, strong) AWSMediatailorDashConfigurationForPut * _Nullable dashConfiguration;

/**
 <p>The configuration for pre-roll ad insertion.</p>
 */
@property (nonatomic, strong) AWSMediatailorLivePreRollConfiguration * _Nullable livePreRollConfiguration;

/**
 <p>The identifier for the playback configuration.</p>
 */
@property (nonatomic, strong) NSString * _Nullable name;

/**
 <p>The maximum duration of underfilled ad time (in seconds) allowed in an ad break.</p>
 */
@property (nonatomic, strong) NSNumber * _Nullable personalizationThresholdSeconds;

/**
 <p>The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. AWS Elemental MediaTailor shows the slate to fill in gaps in media content. Configuring the slate is optional for non-VPAID configurations. For VPAID, the slate is required because MediaTailor provides it in the slots that are designated for dynamic ad content. The slate must be a high-quality asset that contains both audio and video. </p>
 */
@property (nonatomic, strong) NSString * _Nullable slateAdUrl;

/**
 <p>The tags to assign to the playback configuration. </p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

/**
 <p>The name that is used to associate this playback configuration with a custom transcode profile. This overrides the dynamic transcoding defaults of MediaTailor. Use this only if you have already set up custom profiles with the help of AWS Support.</p>
 */
@property (nonatomic, strong) NSString * _Nullable transcodeProfileName;

/**
 <p>The URL prefix for the master playlist for the stream, minus the asset ID. The maximum length is 512 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable videoContentSourceUrl;

@end

/**
 
 */
@interface AWSMediatailorPutPlaybackConfigurationResponse : AWSModel


/**
 <p>The URL for the ad decision server (ADS). This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing, you can provide a static VAST URL. The maximum length is 25,000 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable adDecisionServerUrl;

/**
 <p>The configuration for Avail Suppression. Ad suppression can be used to turn off ad personalization in a long manifest, or if a viewer joins mid-break.</p>
 */
@property (nonatomic, strong) AWSMediatailorAvailSuppression * _Nullable availSuppression;

/**
 <p>The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. </p>
 */
@property (nonatomic, strong) AWSMediatailorBumper * _Nullable bumper;

/**
 <p>The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management. </p>
 */
@property (nonatomic, strong) AWSMediatailorCdnConfiguration * _Nullable cdnConfiguration;

/**
 <p>The configuration for DASH content. </p>
 */
@property (nonatomic, strong) AWSMediatailorDashConfiguration * _Nullable dashConfiguration;

/**
 <p>The configuration for HLS content. </p>
 */
@property (nonatomic, strong) AWSMediatailorHlsConfiguration * _Nullable hlsConfiguration;

/**
 <p>The configuration for pre-roll ad insertion.</p>
 */
@property (nonatomic, strong) AWSMediatailorLivePreRollConfiguration * _Nullable livePreRollConfiguration;

/**
 <p>The identifier for the playback configuration.</p>
 */
@property (nonatomic, strong) NSString * _Nullable name;

/**
 <p>The maximum duration of underfilled ad time (in seconds) allowed in an ad break.</p>
 */
@property (nonatomic, strong) NSNumber * _Nullable personalizationThresholdSeconds;

/**
 <p>The Amazon Resource Name (ARN) for the playback configuration. </p>
 */
@property (nonatomic, strong) NSString * _Nullable playbackConfigurationArn;

/**
 <p>The URL that the player accesses to get a manifest from AWS Elemental MediaTailor. This session will use server-side reporting. </p>
 */
@property (nonatomic, strong) NSString * _Nullable playbackEndpointPrefix;

/**
 <p>The URL that the player uses to initialize a session that uses client-side reporting. </p>
 */
@property (nonatomic, strong) NSString * _Nullable sessionInitializationEndpointPrefix;

/**
 <p>The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. AWS Elemental MediaTailor shows the slate to fill in gaps in media content. Configuring the slate is optional for non-VPAID playback configurations. For VPAID, the slate is required because MediaTailor provides it in the slots designated for dynamic ad content. The slate must be a high-quality asset that contains both audio and video. </p>
 */
@property (nonatomic, strong) NSString * _Nullable slateAdUrl;

/**
 <p>The tags assigned to the playback configuration. </p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

/**
 <p>The name that is used to associate this playback configuration with a custom transcode profile. This overrides the dynamic transcoding defaults of MediaTailor. Use this only if you have already set up custom profiles with the help of AWS Support.</p>
 */
@property (nonatomic, strong) NSString * _Nullable transcodeProfileName;

/**
 <p>The URL prefix for the master playlist for the stream, minus the asset ID. The maximum length is 512 characters.</p>
 */
@property (nonatomic, strong) NSString * _Nullable videoContentSourceUrl;

@end

/**
 
 */
@interface AWSMediatailorTagResourceRequest : AWSRequest


/**
 <p>The Amazon Resource Name (ARN) for the playback configuration. You can get this from the response to any playback configuration request. </p>
 */
@property (nonatomic, strong) NSString * _Nullable resourceArn;

/**
 <p>A comma-separated list of tag key:value pairs. For example: {"Key1": "Value1","Key2": "Value2"}</p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

@end

/**
 <p>A set of tags assigned to a resource. </p>
 Required parameters: [Tags]
 */
@interface AWSMediatailorTagsModel : AWSModel


/**
 <p>A comma-separated list of tag key:value pairs. For example: {"Key1": "Value1","Key2": "Value2"}</p>
 */
@property (nonatomic, strong) NSDictionary<NSString *, NSString *> * _Nullable tags;

@end

/**
 
 */
@interface AWSMediatailorUntagResourceRequest : AWSRequest


/**
 <p>The Amazon Resource Name (ARN) for the playback configuration. You can get this from the response to any playback configuration request. </p>
 */
@property (nonatomic, strong) NSString * _Nullable resourceArn;

/**
 <p>A comma-separated list of the tag keys to remove from the playback configuration. </p>
 */
@property (nonatomic, strong) NSArray<NSString *> * _Nullable tagKeys;

@end

NS_ASSUME_NONNULL_END
