name: Issue Closed

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  cleanup-labels:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'pending-community-response') || contains(github.event.issue.labels.*.name, 'pending-maintainer-response') || contains(github.event.issue.labels.*.name, 'closing soon') || contains(github.event.issue.labels.*.name, 'pending-release') || contains(github.event.issue.labels.*.name, 'pending-triage') }}
    steps:
      - name: Remove unnecessary labels after closing
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY_NAME: ${{ github.event.repository.full_name }}
        run: |
          gh issue edit $ISSUE_NUMBER --repo $REPOSITORY_NAME --remove-label "closing soon" --remove-label "pending-community-response" --remove-label "pending-maintainer-response" --remove-label "pending-release" --remove-label "pending-triage"

  comment-visibility-warning:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            This issue is now closed. Comments on closed issues are hard for our team to see. 
            If you need more assistance, please open a new issue that references this one.
            If you wish to keep having a conversation with other community members under this issue feel free to do so.
