name: Kick off release process

on: [workflow_dispatch]

permissions:
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: "gh pr create --title 'chore: kickoff release' --body 'kickoff release' --head main --base release"
