# This is a basic workflow to help you get started with Actions

name: Notify AWS SDK iOS Release

# Controls when the workflow will run
on:
  # Triggers the workflow on release created (draft) or released (stable) events but only for the main branch
  release:
    types: [created, released]

# Limit the GITHUB_TOKEN permissions
permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run webhook curl command
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WEBHOOK_URL }}
          VERSION: $${{github.event.release.html_url}}
          REPO_URL: ${{github.event.repository.html_url}}
          ACTION_NAME: ${{github.event.action}}
        shell: bash
        run: echo $VERSION | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"action":"'$ACTION_NAME'", "repo":"'$REPO_URL'", "version":"{}"}'
