# This is a basic workflow to help you get started with Actions

name: Notify Comments on Issues

# Controls when the workflow will run
on:
  # Triggers the workflow on comment events on pending response issues
  issue_comment:
    types: [created]

# Limit the GITHUB_TOKEN permissions
permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Exclude comments in PRs and comments made from maintainers
    if: ${{ !github.event.issue.pull_request && !contains(fromJSON('["MEMBER", "OWNER"]'), github.event.comment.author_association) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run webhook curl command
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_COMMENT_WEBHOOK_URL }}
          COMMENT: ${{toJson(github.event.comment.body)}}
          USER: ${{github.event.comment.user.login}}
          COMMENT_URL: ${{github.event.comment.html_url}}
        shell: bash
        run: echo $COMMENT | sed "s/\\\n/. /g; s/\\\r//g; s/[^a-zA-Z0-9 &().,:]//g" | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"comment":"{}", "commentUrl":"'$COMMENT_URL'", "user":"'$USER'"}'
